name = "focusbro-api"
main = "src/index.js"
compatibility_date = "2024-03-24"
account_id = "a1c8a33cbe8a3c9e260480433a0dbb06"

# ── ENVIRONMENT: PRODUCTION ──
[env.production]
# ── DATABASE ──
[[env.production.d1_databases]]
binding = "DB"
database_name = "focusbro-db"
database_id = "f6b1685b-a879-4d42-9c23-a30da614be01"

# ── KEY-VALUE STORE ──
[[env.production.kv_namespaces]]
binding = "KV_CACHE"
id = "732d985fd2b84650aa828f7982ba0f87"
preview_id = "732d985fd2b84650aa828f7982ba0f87"

# Production variables
[env.production.vars]
FRONTEND_URL = "https://main.focusbro-7g0.pages.dev"
JWT_SECRET = "your-secret-key-change-in-production"
PASSWORD_SALT_ROUNDS = "10"
